; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.2 on Thu Sep 02 2021 14:23:45 GMT+0200 (Mitteleuropäische Sommerzeit)
M561 ; clear any bed transform
;G29  ; probe the bed and enable compensation

G28
G1 Z5 H2 F12000
G1 X185 Y350 F30000
G30 P0 X185 Y350 Z-99999
G1 Z5 H2 F12000
G1 X330 Y10 F30000
G30 P1 X330 Y10 Z-99999 
G1 X20 Y10 F30000
G30 P2 X20 Y10 Z-99999 S3
G1 Z5 H2 F30000
G1 H2 Z20 F6000