; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.2 on Thu Sep 02 2021 14:23:45 GMT+0200 (Mitteleuropäische Sommerzeit)

T-1
G10 P0 S-273 R-273 ; set T0 extruder temp
G10 P1 S-273 R-273 ; set T0 extruder temp
G10 P2 S-273 R-273 ; set T0 extruder temp
G10 P3 S-273 R-273 ; set T0 extruder temp
M140 S-273 ; set bed temp