; tfree2.g
; called when tool 2 is freed
;
; generated by RepRapFirmware Configuration Tool v3.3.2 on Thu Sep 02 2021 14:23:45 GMT+0200 (Mitteleuropäische Sommerzeit)

;Drop the bed
G91
G1 Z4 F1000
G90

;Purge nozzle
;M98 P"purge.g"

;Move In
G53 G1 X278.5 Y350 F5000
G53 G1 X278.5 Y400 F5000
G53 G1 X278.5 Y410 F2000
G53 G1 X278.5 Y426.4 F600

;Open Coupler
M98 P"/macros/Coupler - Unlock"

M106 P5 S0

;Move Out
G53 G1 X278.5 Y350 F6000