; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.2 on Thu Sep 02 2021 14:23:45 GMT+0200 (Mitteleuropäische Sommerzeit)
; Wait for set temperatures to be reached
;M116 P1

M106 R2